#!/usr/bin/env bash
# Install and config load balaner

config="

frontend Local_Server
    bind :80
    mode http
    default_backend My_Web_Servers

backend My_Web_Servers
    mode http
    balance roundrobin
    server 3598-web-01  34.148.149.199:80 check
    server 3598-web-02  35.231.224.229:80 check

"
sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4

sudo apt-get -y install haproxy=2.4.\*

sudo echo -e "$config" >> /etc/haproxy/haproxy.cfg

sudo echo -e "\nENABLED=1\n" >> /etc/default/haproxy

sudo service haproxy restart
