#!/usr/bin/env bash
#parse /etc/passwd

file="/etc/passwd"

while IFS=":" read -r f1 f2 f3 f4 f5 f6 f7
do
	printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$f1" "$f3" "$f6" "$f7" "$f2" "$f3"
done < "$file"
