#!/usr/bin/env bash
#print Best School 10 times with international luck.
x=1
while [ $x -le 10 ]
do
	echo $x

	case  $x in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac

	x=$(( x + 1 ))
done
